### ISSUE TITLE
java.lang.NullPointerException: when fast scroll

### ISSUE THREAD

**Issue by MIkeeJY** [falnatsheh/EcoGallery#17]
When fast scroll,this bug happened

java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                        at android.view.View.draw(View.java:16204)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by MIkeeJY** [comment]
I changed it to ViewPager...
